### PR TITLE
Update template overrides guide

### PR DESCRIPTION
**Pull request by ercanozkaya**
* Fix paths
* Fix override data
* Remove old and unnecessary guides

### CODE REVIEW

**Comment by ercanozkaya** [comment]
@stevenrombauts @yiendos Can't find the guide on how to merge this. Do I merge into staging, test there, and then merge again to master? Is production push automatic?

**Comment by stevenrombauts** [comment]
@ercanozkaya Workflow is described in the playbook in the (GitHub Flow for Continuous Integration)[http://www.timble.net/playbook/#github-flow-for-continuous-integration] section. In short: merge branch into staging and test that, then merge branch into master and deploy.

Deployment itself is still not automated: use Git to push to the server, git hook will build and deploy. The original wiki article got archived with the old documentation Assembla space, We put it back into the [GitHub wiki](https://github.com/joomlatools/developer.joomlatools.com/wiki/Deployment) for you. Run those commands and you can deploy staging and master :)

**Comment by johanjanssens** [comment]
@ercanozkaya See also http://support.joomlatools.com/forums/topic/5558 Customer still had feedback based on changed you did.

**Comment by stevenrombauts** [comment]
@ercanozkaya The answer to your question has been revoked :-) To deploy to staging or master, just push the corresponding branches to GitHub. Travis will take care of the rest (see [wiki](https://github.com/joomlatools/developer.joomlatools.com/wiki/Deployment))

**Comment by ercanozkaya** [comment]
Resolves #85

**Pull request merged**
